name: CI
on:
  push:
    branches: 
      - main

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.3
        with:
          linter: pylint

      - name: Simular deploy
        uses: actions/upload-artifact@v4
        with: 
          name: deployzip.zip
          path: |
            **.py
            README.md